### PR TITLE
implement stdout receiver

### PR DESCRIPTION
**Pull request by mblaschke**
add stdout receiver without any rotation and additional file handling, reduced logic for stdout handling

hopefully improves situation for #76

### CODE REVIEW

**Comment by djj0809** [comment]
Hope to see this got merged soon

**Comment by superbrothers** [comment]
I also faced this issue and deployed event-exporter with this patch. It works fine for now.

@mblaschke Great job! 🥳

**Comment by szucsitg** [comment]
@mustafaakin is there anything blocking merging this?

**Comment by avivgold098** [comment]
Looks very promising, @mustafaakin any plan to merge it soon?

**Comment by oded-dd** [comment]
Any update about it?

**Comment by djj0809** [comment]
@Kagan @celalemre @ffahri @omerozkan @serhatcan Can you guys take a look at this? Or if these project is already dead, please let us know at least...

**Pull request merged**
