### PR TITLE
feature: support leader election

### PR DESCRIPTION
**Pull request by youyongsong**
leaderelection mechanism is copied from client-go and controller-runtime.
leaderelection cannot be disabled and configured for now, because I don't think it shuold be disabled or configured by user.

### CODE REVIEW

**Comment by mustafaakin** [comment]
I don't think copy-pasting should be the way to go on this one. And it should be configurable because not everyone has the same requirements, and it can be useful to disable them.

**Comment by youyongsong** [comment]
The copy I means is using the same mechanism instead of the same code.

**Comment by mustafaakin** [comment]
Okay, but we still need it to be configurable.

**Comment by youyongsong** [comment]
> Okay, but we still need it to be configurable.

yes, it makes sense!  I have created an another pr to make it configurable, here's the link: https://github.com/opsgenie/kubernetes-event-exporter/pull/37

**Comment by mustafaakin** [comment]
Merged via #37

**Pull request closed without merging**
