### PR TITLE
Add support for TLS configuration of elasticsearch sink

### PR DESCRIPTION
**Pull request by mheck136**
Hi everyone and thanks for the great work on kubernetes-event-exporter!
I'd like to use the exporter on an [ODFE](https://opendistro.github.io/for-elasticsearch/) cluster. We use self-signed certificates, so we need an option to configure the TLS settings of the elasticsearch client.

I added some options to the elasticsearch configuration, trying to follow the way, TLS is configurable in the kafka sink.

There are basically two points, I'm not sure about:
- Are there other fields that should be configurable regarding elasticsearch and TLS
- When to upgrade the elasticsearch go client, which offers other ways to configure TLS

Happy to get your thoughts on this.

### CODE REVIEW

**Comment by mustafaakin** [comment]
Hello, why it would require updating the go client, what other options would you need?

**Comment by mustafaakin** [comment]
There has been also a PR to skip verifying SSL, so it needs to be adjusted accordingly.

**Comment by mheck136** [comment]
@mustafaakin, I merged the most recent changes from the upstream master, but I did override the already introduced `sslVerificationMode` in favour of the more advanced TLS object, I introduced in the pull request. If you'd rather keep the `sslVerificationMode` property on the top level of the elasticsearch configuration, I will adjust it. But i think it's cleaner to have the property naming in line with the elasticsearch configuration naming.
Updating go-elasticsearch will eventually be necessary the keep up to date with elasticsearch. The next minor release after the one used in this project contains changes regarding the configuration of TLS. That's why I wasn't sure if it would be better to first update go-elasticsearch and then introduce TLS configuration properly. Otherwise the TLS configuration has to be adopted as soon as go-elasticsearch in updated in this project.

**Comment by mustafaakin** [comment]
I think it's fine this way, its more clear. Unless there would be a significant reason to update the elasticsearch client, we can hold off and go with the current configuration for a while. Thanks!

**Comment by mustafaakin** [comment]
Oh @mheck136  can you also change the documentation accordingly?

**Comment by mheck136** [comment]
@mustafaakin , see #36

**Pull request merged**
